# Generated by Django 3.1 on 2021-10-17 10:14

import allauth.account.managers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('account', '0002_email_max_length'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='emailaddress',
            managers=[
                ('objects', allauth.account.managers.EmailAddressManager()),
            ],
        ),
        migrations.AddField(
            model_name='emailaddress',
            name='site',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, to='sites.site'),
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='e-mail address'),
        ),
        migrations.AlterUniqueTogether(
            name='emailaddress',
            unique_together={('site', 'email')},
        ),
    ]
